# Generated by Django 3.2.7 on 2022-09-28 05:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('custId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('custFname', models.CharField(max_length=100)),
                ('custLname', models.CharField(max_length=100)),
                ('custemail', models.EmailField(max_length=254, verbose_name='email address')),
                ('custPhone', models.CharField(default='0000000000', max_length=10, validators=[django.core.validators.MinLengthValidator(10)])),
                ('address', models.CharField(max_length=255)),
                ('productNumber', models.CharField(max_length=100)),
                ('expiryDate', models.DateField()),
                ('amount', models.IntegerField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
