# Generated by Django 3.2.7 on 2022-09-28 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='custemail',
            new_name='custEmail',
        ),
    ]
