# Generated by Django 3.2.7 on 2022-10-10 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_rename_custemail_customer_custemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='message',
            field=models.BooleanField(default=False),
        ),
    ]
