# Generated by Django 3.2.7 on 2022-10-18 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_customer_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='createdBy',
            new_name='technition',
        ),
    ]
