# Generated by Django 3.2.7 on 2022-11-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_remove_customer_productnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='itemQuantity',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
