# Generated by Django 3.2.7 on 2022-11-22 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_customer_itemquantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='product',
            new_name='products',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='technition',
        ),
    ]
