# Generated by Django 3.2.7 on 2022-09-28 05:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('prodId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prodNumber', models.CharField(default=None, max_length=255, null=True, unique=True)),
                ('prodName', models.CharField(max_length=100)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
