# Generated by Django 3.2.7 on 2022-10-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amount',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
