# Generated by Django 3.2.7 on 2022-11-15 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.CharField(blank=True, default='0', max_length=10, null=True),
        ),
    ]
