# Generated by Django 3.2.7 on 2022-09-19 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='empWindalid',
            new_name='empCbid',
        ),
    ]
