# Generated by Django 3.2.7 on 2022-10-05 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0003_rename_custemail_customer_custemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='auditType',
            fields=[
                ('auditTypeId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auditType', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='audit',
            fields=[
                ('auditId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('isActive', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('auditType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit.audittype')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
